2024-06-15 10:38:00,389 - Fatlindi - DEBUG - This is a debug message
2024-06-15 10:38:00,389 - Fatlindi - INFO - This is an info message
2024-06-15 10:38:00,389 - Fatlindi - WARNING - This is a warning message
2024-06-15 10:38:00,389 - Fatlindi - ERROR - This is an error message
2024-06-15 10:38:00,389 - Fatlindi - CRITICAL - This is a critical message
2024-06-15 10:38:00,389 - Fatlindi - ERROR - An exception occurred
Traceback (most recent call last):
  File "/Users/dev1/Desktop/Python/Python Intermediate/PythonLogging/my_logging.py", line 39, in main
    x = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
